apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: donbigi/webapp:v1
          ports:
            - containerPort: 80
          env:
            - name: VAULT_ADDR
              value: http://vault.vault.svc.cluster.local:8200
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-auth-token
                  key: token
